# Generated by Django 5.0.6 on 2024-06-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=255, unique=True)),
                ("Email", models.CharField(max_length=255, unique=True)),
                ("Password", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "ID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("Name", models.CharField(max_length=255, unique=True)),
                ("Amount", models.CharField(max_length=255)),
            ],
        ),
    ]
