# Generated by Django 5.0.6 on 2024-06-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aroma", "0004_users_password_alter_admins_email_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="Password",
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
    ]
