# Generated by Django 5.0.6 on 2024-06-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Aroma", "0002_product_users_remove_admins_id_alter_admins_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="ID",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="storage",
            old_name="ID",
            new_name="id",
        ),
    ]
