# Generated by Django 5.0.6 on 2024-06-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aroma", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "ID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("Name", models.CharField(max_length=255, unique=True)),
                ("Sugar", models.IntegerField(max_length=10)),
                ("Coffee", models.IntegerField(max_length=10)),
                ("Flour", models.IntegerField(max_length=10)),
                ("Chocolate", models.IntegerField(max_length=10)),
                ("Price", models.IntegerField(max_length=10)),
                ("Vertical", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "Username",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("Full_name", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=255, unique=True)),
                ("Phone_Number", models.IntegerField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name="admins",
            name="id",
        ),
        migrations.AlterField(
            model_name="admins",
            name="Username",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "OrderID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("Purchase_amount", models.IntegerField(max_length=10)),
                ("Type", models.BinaryField()),
                (
                    "Products",
                    models.ManyToManyField(related_name="Orders", to="Aroma.product"),
                ),
                (
                    "Username",
                    models.ManyToManyField(related_name="Orders", to="Aroma.users"),
                ),
            ],
        ),
    ]
