# Generated by Django 5.0.6 on 2024-06-27 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aroma', '0006_alter_orders_type_alter_product_vertical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='Name',
        ),
        migrations.AddField(
            model_name='storage',
            name='chocolate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='coffee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='storage',
            name='flour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='sugar',
            field=models.FloatField(default=0),
        ),
    ]
