# Generated by Django 5.0.6 on 2024-06-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aroma', '0007_remove_storage_amount_remove_storage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Type',
            field=models.IntegerField(choices=[(1, 'Take Away'), (2, 'In Person')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Vertical',
            field=models.CharField(choices=[('Cold Drink', 'Cold Drink'), ('Cake', 'Cake'), ('Hot Drink', 'Hot Drink'), ('Food', 'Food')], max_length=10),
        ),
    ]
