# Generated by Django 5.0.6 on 2024-07-02 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aroma", "0010_alter_product_chocolate_alter_product_coffee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
